### ISSUE TITLE
Without Heroku

### ISSUE THREAD

**Issue by Matthww** [jesseditson/reply#1]
Is it possible to run this without Heroku?

**Comment by jesseditson** [comment]
Hey there!

This code is a few years old, so it's possible that the twitter APIs are out of date. That being said, this repo has no dependencies on heroku, the heroku setup is purely an example. If you'd like to run standalone, here's how you would do that:
1. Clone or [download](https://github.com/jesseditson/reply/archive/master.zip) this repo
2. Follow the instructions under "prerequisites" in the README, and update your local runtime.json with the values specified (from your twitter app)
3. Run `node reply.js` from the root directory (this assumes you have node.js installed in the environment you're running in)

Hopefully that helps!

**Comment by Matthww** [comment]
Thanks for the reply 

But I'm running accros this error while running it...

```
nodejs reply.js

module.js:340
    throw err;
          ^
Error: Cannot find module 'config-heroku'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pi/reply-master/reply.js:6:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

**Comment by jesseditson** [comment]
Heh - obviously haven't been paying attention to this repo. That module `config-heroku` does not depend on heroku, it gets its name from the fact that it can simply export config to heroku env vars. If you run `npm install` it should start correctly!

**Comment by Matthww** [comment]
Will try it when I'm at home again!
